version: "3.8"
services:
  api:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    container_name: "buildwise_frontend"
    ports:
      - "3000:3000"
    networks:
      - "workflow"
networks:
  workflow:
    external: true